### ISSUE TITLE
not able to Query using FirebaseRecyclerView 

### ISSUE THREAD

**Issue by SahajRana** [mmazzarolo/firebase-recyclerview#1]
Hey! I had an issue regarding query, 
I was actually trying inflate view in which the Person who is added as friend can be added to recyclerView.

Here's my code.
` @Override
    public void onStart(){
        super.onStart();
        if(EmailPref!=null){

```
        Log.e("SahajLOG", " EmailPref " +EmailPref);
        FriendsData er=new FriendsData();
        er.setEmailPref("sahaj9917730102@gmail");
        final Firebase mFirebaseRef = new Firebase(constants.FIREBASE_URL+"rootssahaj/authGplus");
        Query ref = mFirebaseRef.orderByChild("sahaj9917730102@gmail").equalTo("yes");


        ref.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                Log.e("SahajLOG", " dataSnapshot " + dataSnapshot);
            }

            @Override
            public void onCancelled(FirebaseError firebaseError) {

            }
        });



        FirebaseRecyclerAdapter<FriendsData,FriendsViewHolder> adapter=new FirebaseRecyclerAdapter<FriendsData, FriendsViewHolder>(
                FriendsData.class,
                R.layout.chat_view_list,
                FriendsViewHolder.class,
                ref

        ) {
            @Override
            protected void populateViewHolder(FriendsViewHolder friendsViewHolder, FriendsData s, int i) {
                friendsViewHolder.mName.setText(s.getUserNAME());
                friendsViewHolder.mStatus.setText(s.getStatus());
                Picasso.with(context).load(s.getPicurl()).transform(new CircleTransform()).into(friendsViewHolder.mImageProfile);
            }
        };

        recyclerView.setLayoutManager(new LinearLayoutManager(getActivity()));
        AlphaInAnimationAdapter alphaAdapter = new AlphaInAnimationAdapter(adapter);
        alphaAdapter.setDuration(500);
        alphaAdapter.setInterpolator(new OvershootInterpolator(.5f));
        alphaAdapter.setFirstOnly(false);
        recyclerView.setAdapter(new ScaleInAnimationAdapter(alphaAdapter));


    }



}

public static class FriendsViewHolder extends RecyclerView.ViewHolder{
    ImageView mImageProfile;
    android.widget.TextView mName;
    android.widget.TextView mStatus;

    public FriendsViewHolder(View itemView) {
        super(itemView);
        mImageProfile=(ImageView)itemView.findViewById(R.id.profilePICC);
        mName=(android.widget.TextView)itemView.findViewById(R.id.NameUSER);
        mStatus=(android.widget.TextView)itemView.findViewById(R.id.Status);

    }


}
```

`

the error is : 

`Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "sahaj9917730102@gmail" (class com.rana.sahaj.myyu.FriendsData), not marked as ignorable (5 known properties: , "status", "sahaj", "picurl", "userNAME", "emailPref"])
`
i tried many soln as email is not consistent so i cant define it in FriendsData class 
n i tried to make it ignorable but it shows hat i m duplicating jackson files

`Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.

> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/ASL2.0
>     File1: C:\Users\Sahaj.gradle\caches\modules-2\files-2.1\org.codehaus.jackson\jackson-mapper-asl\1.9.13\1ee2f2bed0e5dd29d1cb155a166e6f8d50bbddb7\jackson-mapper-asl-1.9.13.jar
>     File2: C:\Users\Sahaj.gradle\caches\modules-2\files-2.1\org.codehaus.jackson\jackson-core-asl\1.9.13\3c304d70f42f832e0a86d45bd437f692129299a4\jackson-core-asl-1.9.13.jar`

so what should i do, any solution ?

n my Firebase data screenshot

![screenshot 44](https://cloud.githubusercontent.com/assets/16938202/13937604/2a4a0e0a-efec-11e5-8acd-fe9180da8887.png)

**Comment by mmazzarolo** [comment]
Hello SahajRana, 
I'm sorry, it has been a long time since I created this module, but to me it seems that the problem is that here:

``` java
Query ref = mFirebaseRef.orderByChild("sahaj9917730102@gmail").equalTo("yes");
```

you're trying to order the dataset by an existing field.  
Try removing/changing the `.orderByChild("sahaj9917730102@gmail")`

**Comment by SahajRana** [comment]
Actually I wanted to show friends who are added I.e who have value true for their Id in other person database so how to do that with help of fireRecyclerView bcz it shows all the members

**Comment by mmazzarolo** [comment]
Hello @SahajRana, didn't notice the notification, I'm sorry.
Have you been able to make the recyclerview work?

**Comment by SahajRana** [comment]
yeah! now it works ..
