### ISSUE TITLE
Last version feedback

### ISSUE THREAD

**Issue by mmazzarolo** [mmazzarolo/firebase-recyclerview#3]
Hello there,
anyone available for a feedback on the last version of `firebase-recyclerview`? 
It works fine for me but I didn't test it in depth. 🏄

**Comment by baksoy** [comment]
For starters the compile 'com.firebase:firebase-client-android:x.x.x' need to be changed to   compile "com.google.firebase:firebase-database:9.2.0" at the in Gradle dependency. See https://firebase.google.com/support/guides/firebase-android

**Comment by CristianSarac** [comment]
I am using it in a personal project and so far it is working fine.As the project grows i will test it more thoroughly.

**Comment by mmazzarolo** [comment]
Hey @CristianSarac thank you!  
Glad it's working correctly, I'll close the issue but feel free to comment here or to open a new issue if needed.
