### ISSUE TITLE
"nested" data

### ISSUE THREAD

**Issue by joreilly** [mmazzarolo/firebase-recyclerview#4]
Hi,

Any thoughts on how best to address nested data e.g. the onChildAdded() gets called with entry that contains a key which I then need to use to make another firebase query to get the actual data (still getting up to speed with Firebase database stuff so might be missing something basic.....didn't seem for example like it was possible to do something like a join to pull all the data back?)

Thanks,
John

**Comment by mmazzarolo** [comment]
Hello there, sorry if I'm late!
Unfortunately I can't really understand what you're trying to achieve. 
Could you reword the issue? Thanks!
